version: '3.9'
services:
  wiremock:
    image: "wiremock/wiremock:2.31.0"
    ports:
      - "8999:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/__admin || exit 1"]
      start_period: 10s
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - ../wiremock/mappings:/home/wiremock/input
