version: '3.9'
services:
  service-entertain-user:
    image: "service-entertain-user:latest"
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/V1/entertain/getJoke || exit 1" ]
      start_period: 10s
      interval: 2s
      timeout: 10s
      retries: 3